name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Main Site
        run: |
          curl -L --fail --show-error --silent https://hometax-use.onrender.com > /dev/null

      - name: Ping Crawler API
        run: |
          curl -L --fail --show-error --silent https://hometax-crawler-api.onrender.com > /dev/null
